#!/bin/sh
# A script to install all the packages I want
#   on my machines.
#   git must be preinstalled.

#Setup git
git config --global user.email "josh@joshuasnider.com"
git config --global user.name "Joshua Snider"
git config --global url."https://jsnider3@github.com".insteadOf "https://github.com"
git config --global credential.helper 'cache --timeout=28800'
git config --global push.default simple
git config --global core.autocrlf false
git config --global core.filemode false
git config --global color.ui true

#Clone my rc files.
if [ ! -d "~/Documents/Git" ]; then
  mkdir ~/Documents/Git
  cd ~/Documents/Git
  git clone https://github.com/jsnider3/config.git 
  cd config
  ln -snf `pwd`/.bashrc ~/.bashrc
  ln -snf `pwd`/.vimrc ~/.vimrc
  sudo ln -snf ~/Documents/Git/config/umain_bash /usr/bin/umain
  sudo cp ./sudoers /etc/sudoers
fi
# Add ppa for variety.
# Then update the preinstalled packages.
if [ -z `which variety` ]; then
  sudo add-apt-repository ppa:peterlevi/ppa
fi
# Add ppa for cassandra.
if [ -z `which cqlsh` ]; then
  echo "deb http://debian.datastax.com/community stable main" | \
    sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
fi
# Add ppa for sbt.
if [ -z `which sbt` ]; then
  echo "deb http://dl.bintray.com/sbt/debian /" | \
    sudo tee -a /etc/apt/sources.list.d/sbt.list
fi
# Add ppa for sbt.
if [ -z `which android-studio` ]; then
  sudo apt-add-repository -y ppa:paolorotolo/android-studio
fi
sudo apt-get update -y
sudo apt-get upgrade -y

#Install generically useful software.
BASICS="autoconf automake bridge-utils build-essential cloc cpu-checker curl \
        dos2unix gimp hibernate lamp-server^ libcups2-dev libtool\
        libvirt-bin make markdown pinta pkg-config openssh-server openvpn\
        qemu-kvm spark ubuntu-vm-builder virtualbox-qt libfreetype6-dev\
        ttf-ancient-fonts libegl1-Mesa-dev libgtk2.0-dev gconf-2.0\
        libpulse-dev libxtst-dev libxss-dev libpci-dev libexif-dev\
        libconf2-dev libgnome-keyring-dev libnss3-dev libc++6-dev \
        libc++-dev libc++-helpers libc++-test libc++1 libc++abi-dev\
        libc++abi-test libc++abi1 libstdc++-4.8-dev libstdc++6-4.7-dev\
        libclang-dev ttf-indic-fonts ttf-punjabi-fonts gperf sshpass"
IA32="lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6 libgtk2.0-0:i386\
      libnss3-1d:i386 libnspr4-0d:i386 lib32nss-mdns* libxml2:i386\
      libxslt1.1:i386 libstdc++6:i386"
FILES="unace unrar zip unzip p7zip-full p7zip-rar sqlite3\
       sharutils rar uudeview mpack arj cabextract file-roller"
SECURE="libssl-dev m4 zlib1g-dev"
MEDIA="vlc gstreamer0.10-plugins-ugly gxine libdvdread4\
       totem-mozilla icedax tagtool easytag id3tool lame\
       nautilus-script-audio-convert libmad0 mpg321 gstreamer1.0-libav"
NETWORK="apcupsd bootpc httpie network-manager-openvpn-gnome tftp whois"
EDITORS="eclipse emacs vim-gnome"
WEKA='weka'
UTILITIES="$BASICS $EDITORS $FILES $IA32 $MEDIA $SECURE $NETWORK $WEKA"

#Install every programming language in existence.
CASSANDRA="dsc21"
COBOL="open-cobol"
DB="mongodb mongodb-clients"
DOTNET="monodevelop mono-complete fsharp"
GCC="gcc g++ gfortran clang"
GO="gccgo-go golang-go golang-go.tools"
HASKELL="ghc darcs haskell-platform yesod"
JAVA="android-studio cobertura jflex junit openjdk-7-jdk openjdk-8-jdk"
JAVASCRIPT="npm nodejs nodejs-legacy"
LISP="clisp clisp-doc clisp-dev slime"
OCAML="ocaml ocaml-doc ocaml-findlib opam js-of-ocaml \
       ocaml-native-compilers libpcre-ocaml-dev menhir"
PERL="perl perl-tk"
PYTHON="ipython python3 pylint pypy python-dev \
        python-pip python3-pip python3-bs4 python3-coverage \
        cython virtualenv"
PROLOG="swi-prolog"
RUBY="jekyll ruby-dev rake"
R="littler r-base r-base-dev"
SCALA="scala sbt"
TEX="texworks texlive texlive-full texlive-fonts-extra texinfo xzdec"
SHELLS="csh fish ksh mksh rc tcsh sash"
FP="$HASKELL $LISP $OCAML"
SCRIPTS="$JAVASCRIPT $PERL $PYTHON $RUBY $SHELLS"
LANGUAGES="$CASSANDRA $COBOL $DB $FP $SCRIPTS $DOTNET $GCC $GO $JAVA \
           $PROLOG $R $SCALA $TEX"

#This may take a while.
sudo apt-get install -y $UTILITIES $LANGUAGES 

#Do additional programming language setup.
sudo pip install coverage matplotlib numexpr numpy pandas scipy
cabal update
cabal install primes
opam init -n
eval `opam config env`
opam install batteries core -y
sudo npm install -g coffee-script harp github
sudo gem install mercenary rails

#Chrome
if [ -z `which google-chrome-stable` ]; then
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo dpkg -i google-chrome-stable_current_amd64.deb
  rm google-chrome-stable_current_amd64.deb
fi

#Setup variety
if [ -z `which variety` ]; then
  sudo apt-get install -y variety
  sudo ln -snf /opt/extras.ubuntu.com/variety/bin/variety /usr/bin/variety
  variety
fi

#Add extra workspaces
gsettings set \
  org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 2
gsettings set \
  org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 2

#Finalize
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get autoremove


#Tell user if we need to edit bios for Android emulation.
kvm-ok

#Setup chromium project.
cd ~/Documents/Git
if [ ! -d "~Documents/Git/chromium"]; then
  cd ~/Documents/Git
  cp "~/Documents/Git/config/make_chrome.sh" ./
  sh make_chrome.sh
fi
