#!/bin/sh
# A script to install all the packages I want
#   on my machines.

# Add ppa for variety.
# Then uupdate the preinstalled packages.
sudo add-apt-repository ppa:peterlevi/ppa
sudo apt-get update
sudo apt-get upgrade

BASICS="autoconf automake git libtool make pkg-config"
DOTNET="monodevelop mono-complete fsharp"
GCC="build-essential curl gcc g++ gfortran"
HASKELL="ghc haskell-platform yesod"
JAVA="openjdk-7-jdk openjdk-8-jdk"
OCAML="ocaml ocaml-doc ocaml-findlib opam ocaml-native-compilers libpcre-ocaml-dev"
PERL="perl perl-tk"
PYTHON="python3 pylint pypy python-dev python-numpy python-scipy cython"
PROLOG="swi-prolog"
RUBY="jekyll ruby-dev"
R="r-base r-base-dev"
TEX="texworks texlive texlive-fonts-extra texinfo"

EDITORS="eclipse emacs vim-gnome"
SECURE="libssl-dev m4 zlib1g-dev"
SHELLS="csh fish ksh mksh rc tcsh sash"
FILES="unace unrar zip unzip p7zip-full p7zip-rar \
       sharutils rar uudeview mpack arj cabextract file-roller"
PRETTY="variety"
MEDIA="vlc gstreamer0.10-plugins-ugly gxine libdvdread4 \
       totem-mozilla icedax tagtool easytag id3tool lame \
       nautilus-script-audio-convert libmad0 mpg321 gstreamer1.0-libav"

#Get pre-installed packages up to date.
sudo apt-get update
sudo apt-get upgrade

sudo apt-get install -y $GCC $PYTHON $HASKELL $JAVA $OCAML $PROLOG $RUBY \
                        $TEX $MEDIA $EDITORS $SECURE $SHELLS $FILES \
                        $PRETTY $CHROME $CSHARP $BASICS $PERL $R

cabal install primes
# opam install batteries core

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb

#Finalize
sudo apt-get update
sudo apt-get upgrade
sudo apt-get autoremove

mkdir ~/Documents/Git
cd ~/Documents/Git
git clone https://github.com/jsnider3/config.git 
cd config
ln -snf `pwd`/.bashrc ~/.bashrc
ln -snf `pwd`/.vimrc ~/.vimrc
