#!/bin/sh
# A script to install all the packages I want
#   on my machines.
#   git must be preinstalled.

#Setup git
git config --global user.email "jsnider3@masonlive.gmu.edu"
git config --global user.name "Joshua Snider"
git config --global url."https://jsnider3@github.com".insteadOf "https://github.com"
git config --global credential.helper 'cache --timeout=28800'
git config --global push.default simple

#Clone my rc files.
if [ ! -d "~/Documents/Git" ]; then
  mkdir ~/Documents/Git
  cd ~/Documents/Git
  git clone https://github.com/jsnider3/config.git 
  cd config
  ln -snf `pwd`/.bashrc ~/.bashrc
  ln -snf `pwd`/.vimrc ~/.vimrc
  sudo ln -snf ~/Documents/Git/config/umain_bash /usr/bin/umain
  sudo cp ./sudoers /etc/sudoers
fi
# Add ppa for variety.
# Then update the preinstalled packages.
if [ -z `which variety` ]; then
  sudo add-apt-repository ppa:peterlevi/ppa
fi
sudo apt-get update -y
sudo apt-get upgrade -y

#Install generically useful software.
BASICS="autoconf automake build-essential cloc curl gimp hibernate\
        libtool make pinta pkg-config openssh-server virtualbox-qt"
FILES="unace unrar zip unzip p7zip-full p7zip-rar sqlite3\
       sharutils rar uudeview mpack arj cabextract file-roller"
SECURE="libssl-dev m4 zlib1g-dev"
MEDIA="vlc gstreamer0.10-plugins-ugly gxine libdvdread4 \
       totem-mozilla icedax tagtool easytag id3tool lame \
       nautilus-script-audio-convert libmad0 mpg321 gstreamer1.0-libav"
NETWORK="apcupsd bootpc httpie tftp whois"
EDITORS="eclipse emacs vim-gnome"
UTILITIES="$BASICS $EDITORS $FILES $MEDIA $SECURE $NETWORK"

#Install every programming language in existence.
DOTNET="monodevelop mono-complete fsharp"
GCC="gcc g++ gfortran"
HASKELL="ghc darcs haskell-platform yesod"
JAVA="openjdk-7-jdk openjdk-8-jdk"
JAVASCRIPT="npm nodejs nodejs-legacy"
LISP="clisp clisp-doc clisp-dev slime"
OCAML="ocaml ocaml-doc ocaml-findlib opam js-of-ocaml \
       ocaml-native-compilers libpcre-ocaml-dev menhir"
PERL="perl perl-tk"
PYTHON="python3 pylint pypy python-dev python-numpy python-scipy cython"
PROLOG="swi-prolog"
RUBY="jekyll ruby-dev rake"
R="r-base r-base-dev"
TEX="texworks texlive texlive-full texlive-fonts-extra texinfo"
SHELLS="csh fish ksh mksh rc tcsh sash"
FP="$HASKELL $LISP $OCAML"
SCRIPTS="$JAVASCRIPT $PERL $PYTHON $RUBY $SHELLS"
LANGUAGES="$FP $SCRIPTS $DOTNET $GCC $JAVA $PROLOG $R $TEX"

#This may take a while.
sudo apt-get install -y $UTILITIES $LANGUAGES 

#Do additional programming language setup.
cabal update
cabal install primes
opam init -n
eval `opam config env`
opam install batteries core -y
sudo npm install -g coffee-script
sudo gem install rails

#Chrome
if [ -z `which google-chrome-stable` ]; then
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo dpkg -i google-chrome-stable_current_amd64.deb
  rm google-chrome-stable_current_amd64.deb
fi

#Setup variety
if [ -z `which variety` ]; then
  sudo apt-get install -y variety
  sudo ln -snf /opt/extras.ubuntu.com/variety/bin/variety /usr/bin/variety
  variety
fi

#Add extra workspaces
gsettings set \
  org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 2
gsettings set \
  org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 2

#Finalize
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get autoremove

